on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: linked-issues
      uses: boneskull/more-linked-issues-action@v0.1.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
    # Use the output from the `hello` step
    - name: Get the output 
      run: echo "${{ steps.linked-issues.outputs.links }}"
