on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    
jobs:
  link-issues:
    runs-on: ubuntu-latest
    name: more linked issues!!
    steps:
    - name: link extra issues
      id: linked-issues
      uses: boneskull/more-linked-issues-action@master
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Get the output 
      run: echo "${{ steps.linked-issues.outputs.links }}"
